---
apiVersion: v1
kind: ReplicatinoController
metadata: 
  name: hello-rc
spec:
  replicas: 3
  selector:
    app: hello-world
  template: 
    metadata:
    labels:
    app: hello-world
    spec: 
    containers:
      - name: hello-ctr
        image: jenkins
        ports: 
        - containerPort: 8080
